### ISSUE TITLE
Panic on jwt/jws verify/decrypt with bad JSON headers

### ISSUE THREAD

**Issue by mwitkow** [dvsekhvalnov/jose2go#10]
It is possible to make the `jose.Decode` call panic with a JSON header that's badly formatted.

Take this input:

```go
	parts := []string{}
	for i := 0; i < 3; i++ {
		parts = append(parts, base64url.Encode([]byte(`{"something": 2}`)))
	}
        secret = strings.Join(parts, ".")
        _, err := jose.Decode(secret, publicKey)
```

It will cause
```
goroutine 16 [running]:
testing.func·006()
	/usr/local/go/src/testing/testing.go:441 +0x181
github.com/dvsekhvalnov/jose2go.verify(0xc2081088c0, 0x3, 0x3, 0x9fb3c0, 0xc20811c340, 0x0, 0x0, 0xc20811c340, 0x0, 0x0)
	/home/michal/Private/code/go/src/github.com/dvsekhvalnov/jose2go/jose.go:303 +0x376


github.com/dvsekhvalnov/jose2go.Decode(0xc208108870, 0x44, 0x9fb3c0, 0xc20811c340, 0x0, 0x0, 0xc208105d20, 0x0, 0x0)
	/home/michal/Private/code/go/src/github.com/dvsekhvalnov/jose2go/jose.go:248 +0x126
```

Similarly for `decrypt` method.

The extraction of header values needs validation and error handling.

**Comment by dvsekhvalnov** [comment]
Hi @mwitkow ,

do you mean malformed json string or using unexpected json type (number vs. string)?

**Comment by mwitkow** [comment]
Any json that doesn't have an "alg" field (or "eng"), and possibly if it's
of a different type.

**Comment by dvsekhvalnov** [comment]
I see. Make sense. 

Do you have pull request or just reporting an issue? )

**Comment by skarllot** [comment]
Please no. Just return an error.

**Comment by dvsekhvalnov** [comment]
Hi @skarllot, sorry didn't get your question?

**Comment by skarllot** [comment]
@dvsekhvalnov panic is more difficult to handle than error.
I think that panic should be used only on very exceptional cases, otherwise use error.

**Comment by dvsekhvalnov** [comment]
@mwitkow , @skarllot all fixed. sorry for so long delay.
