### ISSUE TITLE
decode  but not vertify

### ISSUE THREAD

**Issue by notedit** [dvsekhvalnov/jose2go#12]
in  python

i can just use jwt.decode(payload)  without key,  this will just decode and will vertify payload.

how i can do this in jose2go?

**Comment by dvsekhvalnov** [comment]
Hi @notedit ,

can you post link to python library you mentioned, i'll take a look?

In general answer is: no. To decode something you need to provide key. Most likely python library allow you to specify key by some other means.

**Comment by notedit** [comment]
https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jws.py#L108

the key can be  empty  and   set  verify = False

i use this in my  iOS app.

in fact  https://github.com/yourkarma/JWT  support this too.

just  decode and not vertify.

**Comment by notedit** [comment]
i use this feature in my android app too,  i  write a simple java version for my owe use.

hoping have a golang version

**Comment by dvsekhvalnov** [comment]
Is it make any sense in real world? Why do you want to use something without verifying it?

There is no direct way to disable verification. You can try play around: https://github.com/dvsekhvalnov/jose2go#two-phase-validation and somehow capture info from callback.

Or if you strictly dealing with signed token (not encrypted). You can just use `compact` package to extract payload. See https://github.com/dvsekhvalnov/jose2go/blob/master/compact/compact_test.go

**Comment by notedit** [comment]
the client can use some value in the playload

**Comment by notedit** [comment]
ok  got that
