### ISSUE TITLE
Decode without verifying

### ISSUE THREAD

**Issue by elgs** [dvsekhvalnov/jose2go#15]
It sounds weird, but I'm wondering whether it is possible to decode the token without verifying. My scenario is like this. I keep a map of user_id and their keys on the server, so I need to decode the token to get the user_id first, and look up their key to verify it later. 

Currently the Decode function will not decode the token when a key is not provide or is incorrect. I'm hoping it will still decode the token, but return the key error separately. Think about the client can decode the token without the key.

**Comment by dvsekhvalnov** [comment]
Not weird at all :)

See:
https://github.com/dvsekhvalnov/jose2go/blob/master/README.md#two-phase-validation

**Comment by elgs** [comment]
Thank you so much! That completely matches my situation and saved me a lot of coding!
