### ISSUE TITLE
Security vulnerabilities

### ISSUE THREAD

**Issue by nasverdes** [dvsekhvalnov/jose2go#16]
To solve some problems of security related [here](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/), I think this is important:

jose.Decode(token, publicKey) ==>> jose.Decode(token, **Algorithm**, publicKey)

**Comment by dvsekhvalnov** [comment]
Hi @EvertonSalesBranco ,

`jose2go` is not subject for this kind of attack, see unit tests: https://github.com/dvsekhvalnov/jose2go/blob/master/jose_test.go#L86

Though i don't mind contribution if you want to add strict validation.

**Comment by dvsekhvalnov** [comment]
hi @nasverdes , are you good with discussion and solution we discussed in your pull request? Or still have other questions?

**Comment by dvsekhvalnov** [comment]
Closed due to inactivity. Feel free to re-open if more questions.
