### ISSUE TITLE
GCM - PANIC - incorrect nonce length

### ISSUE THREAD

**Issue by alexandrestein** [dvsekhvalnov/jose2go#21]
The package panics if you provide a fake token where you change the length of the third section.

I made a very simple example using the **GCM** example in the **README**.
I removed one char from _FePGIeMhhwVBPGLV_ which is the the third section.

```go
sharedKey := []byte{194, 164, 235, 6, 138, 248, 171, 239, 24, 216, 11, 22, 137, 199, 215, 133}
fakeToken := "eyJhbGciOiJBMTI4R0NNS1ciLCJlbmMiOiJBMTI4R0NNIiwiaXYiOiItMTBMX3E4aVRPNlpuZ3Y4IiwidGFnIjoiUzlwSUZSV2hzOEp3djJ3VE82OF9vUSJ9.u5t1-HXQkDuSQfsz0sSV-g.FePGIeMhhwVBPGV.ciJXdFyuQ5ZiJUC-uPPigxa3._WG5rSsOxkujn_fzYvDp0Q"
jose.Decode(fakeToken, sharedKey)
```

This returns:
```
panic: cipher: incorrect nonce length given to GCM

goroutine 1 [running]:
crypto/aes.(*gcmAsm).Open(0xc4200a6a20, 0x0, 0x0, 0x0, 0xc42001a480, 0xb, 0xc, 0xc42001c390, 0x22, 0x30, ...)
	/usr/lib/go/src/crypto/aes/aes_gcm.go:137 +0x5c3
...
exit status 2
```

I believe checking the length before submitting to **crypto/aes.Open** would solve this.

**Comment by dvsekhvalnov** [comment]
Hi @alexandrestein , thanks for reporting this.  Mind pull request with unit test?

I'll be able to merge next week (on vacation :)

**Comment by alexandrestein** [comment]
I hope this will be what you expect.

Enjoy your vacation. :sun_with_face:
