### ISSUE TITLE
How to decode zip DEFLATE compression token?

### ISSUE THREAD

**Issue by alanywlee** [dvsekhvalnov/jose2go#25]
I am trying to parse a RS256 encoded token from java, it could be successfully decoded by public key in java using the following java code

`Jwts.parser().setSigningKey(publicKey).parseClaimsJws(jwt);`

Moreover, It could be decoded by golang example described at https://github.com/dvsekhvalnov/jose2go

```
package main

import (
    "fmt"
    "io/ioutil"
    Rsa "github.com/dvsekhvalnov/jose2go/keys/rsa"
    "github.com/dvsekhvalnov/jose2go"
)

func main() {

    token := "eyJhbGciOiJSUzI1NiIsImN0eSI6InRleHRcL3BsYWluIn0.eyJoZWxsbyI6ICJ3b3JsZCJ9.NL_dfVpZkhNn4bZpCyMq5TmnXbT4yiyecuB6Kax_lV8Yq2dG8wLfea-T4UKnrjLOwxlbwLwuKzffWcnWv3LVAWfeBxhGTa0c4_0TX_wzLnsgLuU6s9M2GBkAIuSMHY6UTFumJlEeRBeiqZNrlqvmAzQ9ppJHfWWkW4stcgLCLMAZbTqvRSppC1SMxnvPXnZSWn_Fk_q3oGKWw6Nf0-j-aOhK0S0Lcr0PV69ZE4xBYM9PUS1MpMe2zF5J3Tqlc1VBcJ94fjDj1F7y8twmMT3H1PI9RozO-21R0SiXZ_a93fxhE_l_dj5drgOek7jUN9uBDjkXUwJPAyp9YPehrjyLdw"

    keyBytes, err := ioutil.ReadFile("public.key")

    if(err!=nil) {
        panic("invalid key file")
    }

    publicKey, e:=Rsa.ReadPublic(keyBytes)

    if(e!=nil) {
        panic("invalid key format")
    }

    payload, headers, err := jose.Decode(token, publicKey)

    if(err==nil) {
        //go use token
        fmt.Printf("\npayload = %v\n",payload)

        //and/or use headers
        fmt.Printf("\nheaders = %v\n",headers)
    }
} 

```

I just replaced access token string and public key file, it successfully decoded my token and got

```
payload = xڪVJ�(P�245��4��42�Q�M�MJ-�LQ�R
-�P�  �%��╗�}��|\]���{���lZ�R-   ��

headers = map[alg:RS256 zip:DEF]

```

I doubt the problem is more likely because of token payload is "zip DEFLATE compression".
But I only found example to generate a zip encrypted token, but no example to decode it.

Could anyone help me to decode zip DEFLATE compression token?

Any comment is highly appreciated.

Best regards,

Alan

**Comment by dvsekhvalnov** [comment]
HI @alanywlee ,

mind provide token you have issues with decoding? The one you have in your golang example:
`eyJhbGciOiJSUzI1NiIsImN0eSI6InRleHRcL3BsYWluIn0.eyJoZWxsbyI6ICJ3b3JsZCJ9.NL_dfVpZkhNn4bZpCyMq5TmnXbT4yiyecuB6Kax_lV8Yq2dG8wLfea-T4UKnrjLOwxlbwLwuKzffWcnWv3LVAWfeBxhGTa0c4_0TX_wzLnsgLuU6s9M2GBkAIuSMHY6UTFumJlEeRBeiqZNrlqvmAzQ9ppJHfWWkW4stcgLCLMAZbTqvRSppC1SMxnvPXnZSWn_Fk_q3oGKWw6Nf0-j-aOhK0S0Lcr0PV69ZE4xBYM9PUS1MpMe2zF5J3Tqlc1VBcJ94fjDj1F7y8twmMT3H1PI9RozO-21R0SiXZ_a93fxhE_l_dj5drgOek7jUN9uBDjkXUwJPAyp9YPehrjyLdw`

is not deflated.

**Comment by dvsekhvalnov** [comment]
If you looking for example of deflated token, the one can be found in unit tests: https://github.com/dvsekhvalnov/jose2go/blob/master/jose_test.go#L2121

**Comment by alanywlee** [comment]
Dear dvsekhvalnov,

Thanks for your quick response.

My deflated token is as following:
`eyJhbGciOiJSUzI1NiIsInppcCI6IkRFRiJ9.eNqqVkqtKFCyMjQ1s7Q0sbA0MtFRyk3NTUot8kxRslIKLbZQggn4JeamAoUcfRz99HxcXRWeze172tr4bFq7Ui0AAAD__w.jBXD4LT4aq4oXTgDoPkiV6n4QdSZPZI1Z4J8MWQC42aHK0oXwcovEU06dVbtB81TF-2byuu0-qi8J0GUttODT67k6gCl6DV_iuCOV7gczwTcvKslotUvXzoJ2wa0QuujnjxLEE50r0p6k0tsv_9OIFSUZzDksJFYNPlJH2eFG55DROx4TsOz98az37SujZi9GGbTc9SLgzFHPrHMrovRZ5qLC_w4JrdtsLzBBI11OQJgRYwV8fQf4O8IsMkHtetjkN7dKgUkJtRarNWOk76rpTPppLypiLU4_J0-wrElLMh1TzUVZW6Fz2cDHDDBACJgMmKQ2pOFEDK_vYZN74dLCF5GiTZV6DbXhNxO7lqT7JUN4a3p2z96G7WNRjblf2qZeuYdQvkIsiK-rCbSIE836XeY5gaBgkOzuEvzl_tMrpRmb5Oox1ibOfVT2KBh9Lvqsb1XbQjCio2CLE2ViCLqoe0AaRqlUyrk3n8BIG-r0IW4dcw96CEryEMIjsjVp9mtPXamJzf391kt8Rf3iRBqwv3zP7Plg1ResXbmsFUgOflAUPcYmfLug4W3W52ntcUlTHAKXrNfaJL9QQiYAaDukG-ZHDytsOWTuuXw7lVxjt-XYi1VbRAIjh1aIYSELEmEpE4Ny74htQtywYXMQNfJpB0nNn8IiWakgcYYMJ0TmKM
`


I found the unit test example at
https://github.com/dvsekhvalnov/jose2go/blob/master/jose_test.go#L2121
is decoded using private key. Even though I am not sure if there is any different to decode by public key?

**Comment by dvsekhvalnov** [comment]
@alanywlee, your token is not encrypted one, it is JWS - signed token with RS256 algo and somehow specifying it is deflated.  

The one in unit tests on line 2121 - is encrypted (JWE) + deflated token.

The thing is JWS spec is not defining compressed payload at all:  https://tools.ietf.org/html/rfc7515
Compressed payload is only defined for JWE: https://tools.ietf.org/html/rfc7516#section-4.1.3

Though probably nothing wrong with compressing payload for signed tokens (JWS),  I don't know any jws implementation that supports it, not to mention it is non standard, because nothing defines how to process them: sign before compress or compress before sign, e.t.c.

I'm curious how did you get the token? What implementation generated it?

**Comment by dvsekhvalnov** [comment]
@alanywlee , so i think you can do next thing (deflate your content manually):

```go
payload, headers, err := jose.Decode(token,key)



```

**Comment by alanywlee** [comment]
Dear dvsekhvalnov,

Thanks for your great help.

You are right, it seems my token is jws, so sorry I used to think  jws is one kind of jwt.
The test token is coming from a joint project with single signed on mechanism.
I was informed the token could be simply decoded using java packet jjwt.0.9.0.jar like

`Jwts.parser().setSigningKey(publicKey).parseClaimsJws(jwt);
`

However, my service is writeen in golang, and not able to use Java package.

I tried your suggestion with slightly modification:

```
        payload, headers, err := jose.DecodeBytes(token, publicKey)
        // and deflate payload, or check headers first, than deflate
        deflated, e := ioutil.ReadAll(flate.NewReader(bytes.NewReader(payload)))

```

However, it was unable to decode my payload and got error message as:

`ioutil.ReadAll failed: flate: corrupt input before offset 5
`

I believe the problem is "JWS spec is not defining compressed payload at all"
I checked the github of jwtk 

https://github.com/jwtk/jjwt#jws-create-compression
```
Note that Compression is not a standard feature for JWS and is not likely to be supported by other JWT libraries.

Please see the main section to see how to compress and decompress JWTs.

```

https://github.com/jwtk/jjwt#compression


```
   Jwts.builder()
   
   .compressWith(CompressionCodecs.DEFLATE) // or CompressionCodecs.GZIP

```

Since I can decode token without specified decompression algorithm in Java. 
Is it possible DEFLATE codec is incompatible between Java/Golang?

**Comment by dvsekhvalnov** [comment]
@alanywlee i don't think think deflate or gzip really incompatible, probably there are extra stuff written in addition to "pure" deflate stream.  Let me take a look into jwtk project and how it is doing compression.

**Comment by dvsekhvalnov** [comment]
@alanywlee took a look into https://github.com/jwtk, 2 things:

1. yes it's do compress before sign, which is good, you just need to figure out how to decompress payload you getting back from jose2go

2.https://github.com/jwtk/jjwt/blob/master/impl/src/main/java/io/jsonwebtoken/impl/compression/DeflateCompressionCodec.java  - is really not doing RFC1951 defined compatible compression (the one that defined with JWE). It using default compression and including ZLIB headers which producing non "pure" deflate stream. (should be compression level = DEFLATE, and no wrap headers).

**Comment by dvsekhvalnov** [comment]
You can try to decompress payload with https://golang.org/pkg/compress/zlib/ package, something like:
```golang
z, err := zlib.NewReader(bytes.NewReader(payload))
decompressedPayload, err := ioutil.ReadAll(z)
```

**Comment by alanywlee** [comment]
Dear dvsekhvalnov,

Thanks for your great help. I tried your suggestion

```
z, err := zlib.NewReader(bytes.NewReader(payload))
decompressedPayload, err := ioutil.ReadAll(z)
```
but err not nil got error for ioutil.ReadAll


`unexpected EOF 
`


I used to believe it failed.
But I print  unzip payload anyway


`fmt.Printf("\payload = %v\n", string(decompressedPayload))`


and found it actually got the original payload successfully, but being confused by mysterious "unexpected EOF"

Probably because payload is an UTF-8 encoded string.

I checked stackoverflow and found 
https://stackoverflow.com/questions/51105792/golang-unexpected-eof

```
    rb, err := ioutil.ReadAll(dc)
    if err != nil {
        if err != io.EOF && err != io.ErrUnexpectedEOF {
            log.Fatalf("Err %v\n read %v", err, rb)
        }
    }

```

I doubt ignoring ErrUnexpectedEOF is a standard way to read UTF-8 string?

**Comment by dvsekhvalnov** [comment]
Hm.. interesting, can you share full code that decodes and decompressing it? 

BTW, why don't you use some other library on java side that complies to standards? There are plenty reference implementations available.

**Comment by alanywlee** [comment]
Dear dvsekhvalnov,

The following is the full code of decode and decompressing

```
    payload, headers, err := jose.DecodeBytes(token, publicKey)
    if err==nil {
        z, err := zlib.NewReader(bytes.NewBuffer(payload))
        defer z.Close()
        if err==nil {
            deflated, e := ioutil.ReadAll(z)
            if e != io.EOF && e != io.ErrUnexpectedEOF {
                panic(fmt.Sprintf("Err %v\n read %v\n", err, deflated))
            }
            fmt.Printf("\ndeflated = %v\n", string(deflated))
        }
        fmt.Printf("\npayload = %v\n", payload)
        fmt.Printf("\nheaders = %v\n", headers)
    }
```

I am not aware it is possible to do "Golang call java" before.
However, pure golang is definitely my preferred.

Thanks for your great support again...

**Comment by alanywlee** [comment]
Dear dvsekhvalnov,

I agree with you about the theory of checksum unavailable, looks more likely it's a bug in Java package.
I don't know why my joint project using a wired jwt, probably just because java users all using the same package not be aware of incompatibility .

**Comment by dvsekhvalnov** [comment]
@alanywlee , is there is something i can help further with given issue?

**Comment by dvsekhvalnov** [comment]
Closing this one. Feel free to re-open if more questions.
