### ISSUE TITLE
Missing tag for 1.4 and 1.5

### ISSUE THREAD

**Issue by zhsj** [dvsekhvalnov/jose2go#29]
Hi, the README says "Current version is 1.5." However there's no such tag. Would you mind to create a tag?

**Comment by dvsekhvalnov** [comment]
Hi @zhsj, sure thing, thanks for catching it.

**Comment by dvsekhvalnov** [comment]
Here you go @zhsj .

**Comment by zhsj** [comment]
It seems go module fails to find 1.5...

```
$ GOPROXY=direct go get github.com/dvsekhvalnov/jose2go@v1.5
go get github.com/dvsekhvalnov/jose2go@v1.5: no matching versions for query "v1.5"
```

A guess is that it wants semver pattern, like v1.5.0? Not sure however..

**Comment by zhsj** [comment]
Ha it does say so, https://golang.org/ref/mod#versions

> For example, v0.0.0, v1.12.134, v8.0.5-pre, and v2.0.9+meta are valid versions.

**Comment by dvsekhvalnov** [comment]
mmm... want me to add one more for `v1.5.0` @zhsj  ?

**Comment by zhsj** [comment]
> mmm... want me to add one more for `v1.5.0` @zhsj ?

Yes, please. So it works for Go modules :)

**Comment by dvsekhvalnov** [comment]
Here we go, enjoy your new tag @zhsj :)

**Comment by zhsj** [comment]
Thanks, it works for Go modules now.

https://pkg.go.dev/github.com/dvsekhvalnov/jose2go?tab=versions
