### ISSUE TITLE
Possible to get token.Header["alg"] for JWT vulnerability?

### ISSUE THREAD

**Issue by pandex** [dvsekhvalnov/jose2go#3]
How does one check to make sure the token returned in the Authorization Bearer from the browser is not set to "none"?  Something like this:

    token := r.Header.Get("Authorization")[7:]

    keyBytes, err := ioutil.ReadFile("file/path/to/privateKey")
     if err != nil {
	     panic("invalid key file")
    }

     privKey, e := Rsa.ReadPrivate(keyBytes)
     if e != nil {
	     panic("invalid key format")
    }

     j, err := jose.Decode(token, privKey)

     fmt.Println(j.Header["alg"]) // <-- Want to check for algo = "" vulnerability here

Or if the token header is: 
    {
       "alg": "RSA-OAEP",
       "enc": "A256GCM"
    }
we don't have yo worry about the JWT alg:none problem?

**Comment by dvsekhvalnov** [comment]
Hi @pandex , are you referring to this vulnerability: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/ ?

If so, all have been verified and patched two months ago. Make sure you are using latest version from github.

'plaintext' algorithm expects `nil` key and `empty` signature. So your code looks good to me since you are explicitly passing not `nil` rsa key, library knows you are expecting RSA algo.

**Comment by dvsekhvalnov** [comment]
Or are you asking for ability to get headers from token?  `jose.Decode(..)` returns payload, not returning headers right now.

Though i was thinking to return both just today. Are looking for this feature? E.g. `payload, headers = jose.Decode(...)`

**Comment by pandex** [comment]
Yes, exactly, it would be great to get 

    payload, headers = jose.Decode(…)
type of a peek at the header info, for other purposes of confirmation, tracking, etc. 

By the way, one other related question. In then example above

    privKey, e := Rsa.ReadPrivate(keyBytes)

privKey is of type *rsa.PrivateKey, correct?

If I were to put that value into a struct or var like 

    type Pk struct {
        P *rsa.PrivateKey
    } 
or

    var myPK *rsa.PrivateKey
Go complains about not knowing *rsa*. What am I doing wrong? 
Thanks.

**Comment by dvsekhvalnov** [comment]
@pandex don't you forget to import 'crypto/rsa' ?  You can post some test code, i'll try to take a look.

Ok, i'll schedule header access feature for next version.

**Comment by dvsekhvalnov** [comment]
@pandex , check out latest version and doc, added headers map as return value from jose.Decode() method. See if it is acceptable interface for you case.

**Comment by pandex** [comment]
Thanks, give me a day or two, I'm on vacation. :)

**Comment by dvsekhvalnov** [comment]
@pandex , happy with new interface to get headers?

**Comment by pandex** [comment]
Testing of that part of the code isn't done yet (for other unrelated reasons) but I do use the "alg" part of the headers to check for "" and the type of token being processed (which depends on the algo used in my case). Headers work, thank you.
