### ISSUE TITLE
Security vulnerability disclosure

### ISSUE THREAD

**Issue by mschwager** [dvsekhvalnov/jose2go#31]
Hi there,

I'd like to report a potential security vulnerability in this repository. Using GitHub's private reporting would be easiest:

- [Privately reporting a security vulnerability
](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability)
- [Configuring private vulnerability reporting for a repository
](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)

If that doesn't work, would you mind suggesting an alternative?

**Comment by dvsekhvalnov** [comment]
@mschwager forgot to mention in email, strict alg validation (aka 'extected alg'), can be done with 

https://github.com/dvsekhvalnov/jose2go#two-phase-validation

may be need more docs on it with some helpers.

**Comment by dvsekhvalnov** [comment]
Fixed as part of v1.6 release.
Notes https://github.com/dvsekhvalnov/jose2go#customizing-library-for-security

**Comment by burningalchemist** [comment]
Hey @dvsekhvalnov, could you please create a tag for `v1.6` whenever you have some time? 😃

**Comment by dvsekhvalnov** [comment]
@burningalchemist sure thing, added :)
