### ISSUE TITLE
Tag for 1.2?

### ISSUE THREAD

**Issue by tianon** [dvsekhvalnov/jose2go#7]
The readme mentions that 1.2 is the current version, but there isn't a tag for it -- is that just referring to that being the "in development" version, or was the tag simply an oversight? :smile:

**Comment by dvsekhvalnov** [comment]
That's current `master` :) 

Do you want me to add tag?

**Comment by tianon** [comment]
A tag would be awesome to signal that 1.2 is finished and "released"; I've
packaged the library in Debian (at 1.1), and I'd like to avoid packaging a
snapshot of master to get us to 1.2. :smile:

**Comment by dvsekhvalnov** [comment]
@tianon here you go, enjoy v1.2 tag :)

feel free to close if happy )

**Comment by tianon** [comment]
Thrilled; thanks! :dancer:
